site_name: DHIS2 Documentation
site_description: Official documentation of the DHIS 2 platform
site_author: DHIS2 Documentation Team
# site_url sets the canonical url - we want this to point to the latest version
site_url: 'https://docs.dhis2.org/2.34/<language>/'
copyright: 'Copyright &copy; 2008-2020 DHIS2 Team'
google_analytics: ['UA-157707339-2', 'docs.dhis2.org']
# edit_uri: ''
repo_url: https://github.com/dhis2/dhis2-docs
repo_name: 'dhis2-docs on GitHub'
# Query string example
# edit_uri: tree/master/src/commonmark/en/content/
use_directory_urls: false
# docs_dir:

extra:
    dhis2_version: '<version>'
    dhis2_versions:
        - 'master'
        - '2.35'
        - '2.34'
        - '2.33'
        - '2.32'
        - '2.31'
        - '2.30'
        - '2.29'
    dhis2_language: '<language>'
    dhis2_languages:
        en: 'English'
        fr: 'Français'
        es_419: 'Español (latinoamerica)'
        pt: 'Português'
    social:
      - icon: fontawesome/brands/github
        link: https://www.github.com/dhis2
        name: DHIS2 source code on GitHub
      - icon: fontawesome/brands/docker
        link: https://hub.docker.com/repository/docker/dhis2
        name: DHIS2 on Docker
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/dhis_2
        name: DHIS2 on Twitter
      - icon: fontawesome/brands/facebook
        link: https://www.facebook.com/dhis2
        name: DHIS2 on Facebook
      - icon: fontawesome/brands/discourse
        link: https://community.dhis2.org
        name: DHIS2 Community

theme:
    name: material
    logo: 'resources/images/logo.svg'
    favicon: 'resources/images/favicon.ico'
    features:
      - navigation.tabs
      - navigation.instant
    custom_dir: 'theme'
    palette:
      primary: 'white'
      accent: 'blue'
    language: '<language-no-region>'

# our css
extra_css:
    - resources/css/mkdocs_dhis2.css

extra_javascript:
    - resources/javascript/config.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search
    - edit_url

markdown_extensions:
    - codehilite:
        guess_lang: false
    - markdown_captions
    - toc:
        permalink: true
        toc_depth: 3
    - attr_list
    - def_list
    - footnotes
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.inlinehilite:
        custom_inline:
          - name: math
            class: arithmatex
            format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tilde
    - pymdownx.tabbed
    - pymdownx.tasklist:
        custom_checkbox: true



# output when building
site_dir: ../../target/commonmark/<language>/


nav:
